path:
  ckpt_path: "./output_sdsa_ende_res_st/ckpt/LJSpeech"
  log_path: "./output_sdsa_ende_res_st/log/LJSpeech"
  result_path: "./output_sdsa_ende_res_st/result/LJSpeech"
optimizer:
  batch_size: 1
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 10
  anneal_steps: [10, 20, 30]
  anneal_rate: 0.3
step:
  total_step: 30
  log_step: 100
  synth_step: 1
  val_step: 1
  save_step: 10
